### ISSUE TITLE
Panic occurs for using Unix sockets

### ISSUE THREAD

**Issue by lamchakchan** [letsencrypt/unbound_exporter#62]
## Description
When trying unix socket for the `remote-control` interface, the exporter has no way to be configured to input the unix socket address without a panic.  Looks the the use of `Parse()` from `net/url` fails to recognize the scheme for a target of `unix:///var/run/unbound/control.sock`.

## Unbound Configuration

```
server:
    ...
remote-control:
    control-enable: yes
    control-use-cert: no
    control-interface: "/var/run/unbound/control.sock"
```

## Command

`unbound-exporter -unbound.host unix:///var/run/unbound/control.sock`

## Error

```
level=info ts=2023-10-30T21:31:55.062Z caller=unbound_exporter.go:509 Startingunbound_exporter=(MISSING)
panic: open /etc/unbound/unbound_server.pem: no such file or directory

goroutine 1 [running]:
main.main()
```
